apiVersion: v1
kind: Pod
metadata:
  name: myapp 
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        name: nginxconfig
        subPath: nginx.conf 
  volumes:
    - name: nginxconfig
      configMap:
        name: nginxconfig
        items:
          - key: nginx.conf
            path: nginx.conf
